import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    // Auth
    'auth.subtitle': '加入時尚社群，分享你的穿搭風格',
    'auth.login': '登入',
    'auth.signup': '註冊',
    'auth.email': '電子信箱',
    'auth.emailPlaceholder': '你的電子信箱',
    'auth.password': '密碼',
    'auth.passwordPlaceholder': '你的密碼',
    'auth.passwordTooShort': '密碼至少需要8個字元',
    'auth.passwordComplexity': '密碼必須包含大寫字母、小寫字母和數字',
    'auth.setPassword': '設定密碼',
    'auth.name': '姓名',
    'auth.namePlaceholder': '你的姓名',
    'auth.gender': '性別',
    'auth.male': '男性',
    'auth.female': '女性',
    'auth.other': '其他',
    'auth.preferNotToSay': '不願透露',
    'auth.birthday': '生日',
    'auth.country': '國家',
    'auth.selectCountry': '選擇國家',
    'auth.loggingIn': '登入中...',
    'auth.signingUp': '註冊中...',
    'auth.continueWithGoogle': '使用 Google 繼續',
    'auth.orDivider': '或',

    // Welcome Dialog
    'welcome.title': '歡迎加入 StyleShare！',
    'welcome.intro': '先去社群看看大家最近穿什麼吧，按下每則貼文中的 Try 即可換上其他人的穿搭哦！',
    'welcome.tryNewStyle': '如果您想了解你搭上某個風格後的樣子，可以到虛擬試穿中的試新風格。',
    'welcome.tryNewItem': '如果您有喜歡的單品照，可以到虛擬試穿中的試穿單品來試用單品。',
    'welcome.tryModelOutfit': '如果您有看到鍾意的 model 照，可以到虛擬試穿中的試模特穿搭來換上模特穿搭。',
    'welcome.getStarted': '開始探索',

    // Header
    'header.home': '首頁',
    'header.virtualTryOn': '虛擬試穿',
    'header.community': '社群',
    'header.brands': '品牌',
    'header.celebrities': '名人',
    'header.login': '登入',
    'header.logout': '登出',
    'header.tryNewStyle': '試新風格',
    'header.tryNewItem': '試穿單品',
    'header.tryModelOutfit': '試模特穿搭',
    'header.outfitRating': '穿搭評分',
    'header.notificationCenter': '通知中心',
    'header.profile': '個人頁面',
    'header.adminDashboard': '管理員後台',
    'header.user': '用戶',

    // Outfit Rating
    'outfitRating.title': '穿搭評分',
    'outfitRating.subtitle': '上傳你的穿搭照，讓 AI 為你評分並提供專業建議',
    'outfitRating.uploadPhoto': '上傳穿搭照片',
    'outfitRating.uploadHint': '點擊上傳或拖放圖片',
    'outfitRating.rateButton': '開始評分',
    'outfitRating.analyzing': '分析中...',
    'outfitRating.noPhoto': '請先上傳照片',
    'outfitRating.uploadFirst': '請先上傳您的穿搭照片',
    'outfitRating.loginRequired': '請先登入以使用穿搭評分功能',
    'outfitRating.error': '評分失敗',
    'outfitRating.tryAgain': '請稍後再試',
    'outfitRating.detailedFeedback': '詳細建議',
    'outfitRating.waitingForPhoto': '上傳照片後將在此顯示評分結果',

    // Hero
    'hero.title1': '試穿室',
    'hero.title2': '',
    'hero.subtitle': '以前的你可能不知道這樣穿你能夠多好看',
    'hero.onlineTryOn': '線上試穿',
    'hero.tagline': '別再買錯東西啦！',
    'hero.experience': '試模特穿搭',
    'hero.tryNewStyle': '試新風格',
    'hero.community': '穿搭社群',

    // Virtual Try-On
    'virtualTryOn.title': '虛擬試穿體驗',
    'virtualTryOn.personalPhoto': '全身照',
    'virtualTryOn.uploadPhoto': '上傳清晰照片',
    'virtualTryOn.fashionItems': '精選時尚單品',
    'virtualTryOn.selectOutfit': '選擇你喜歡的穿搭',
    'virtualTryOn.result': '試穿結果',
    'virtualTryOn.startTryOn': '開始虛擬試穿',
    'virtualTryOn.processingPercent': '在換衣服，等一下啦 {{percent}}%',
    'virtualTryOn.cases': '試穿案例',
    'virtualTryOn.caseDescription': '見證專屬訂製級的完美呈現效果',
    'virtualTryOn.loginRequired': '請先登入',
    'virtualTryOn.loginRequiredDesc': '您需要先登入才能使用虛擬試穿功能',
    'virtualTryOn.shareTitle': '我的虛擬試穿成果',
    'virtualTryOn.shareDescription': '看看我的虛擬試穿效果！',
    'virtualTryOn.shareSuccess': '分享成功',
    'virtualTryOn.shareSuccessDesc': '試穿結果已成功分享',
    'virtualTryOn.remainingTryons': '剩餘試穿次數',
    'virtualTryOn.admin': '管理員',
    'virtualTryOn.unlimited': '無限次數',
    'virtualTryOn.limitReached': '已達使用上限',
    'virtualTryOn.limitReachedDesc': '您已使用完所有 {count} 次虛擬試穿機會',
    'virtualTryOn.tryonSuccess': '試穿成功！',
    'virtualTryOn.tryonSuccessDesc': '您的虛擬試穿照片已生成。剩餘試穿次數: {remaining} / {total}',
    'virtualTryOn.processing': '處理中',
    'virtualTryOn.processingDesc': '工作流程已啟動，為您查詢結果中…',
    'virtualTryOn.processingFailed': '處理失敗',

    // Better Than Model
    'betterThanModel.title': '試試模特穿搭',
    'betterThanModel.modelOutfits': '模特穿搭照',
    'betterThanModel.selectModelOutfit': '選擇你鍾意的模特穿搭照',
    'betterThanModel.clickToUpload': '點擊上傳照片',
    'betterThanModel.transforming': '在換衣服，等一下啦',
    'betterThanModel.estimatedTime': '(預計時間: 2 分鐘)',
    'betterThanModel.transformNewStyle': '開始換穿搭',

    // Outfit Grid
    'outfitGrid.title': '熱門穿搭',
    'outfitGrid.titleHighlight': '分享',
    'outfitGrid.subtitle': '探索社群中最受歡迎的時尚穿搭，從中獲得靈感，創造屬於你的獨特風格',
    'outfitGrid.loadMore': '查看更多穿搭',
    'outfitGrid.outfits.asianSweet': '亞洲甜美風格',
    'outfitGrid.outfits.europeanClassic': '歐式經典風衣',
    'outfitGrid.outfits.koreanModern': '韓式現代韓服',
    'outfitGrid.outfits.bohemian': '波西米亞風情',
    'outfitGrid.outfits.nordicMinimal': '北歐極簡風格',
    'outfitGrid.outfits.urbanStreet': '都市街頭潮流',
    'outfitGrid.outfits.businessElegant': '優雅商務風格',
    'outfitGrid.outfits.casualComfort': '休閒舒適穿搭',
    'outfitGrid.outfits.eveningElegant': '晚宴典雅造型',
    'outfitGrid.tags.asian': '亞洲風',
    'outfitGrid.tags.sweet': '甜美',
    'outfitGrid.tags.floral': '花卉',
    'outfitGrid.tags.fresh': '清新',
    'outfitGrid.tags.european': '歐美風',
    'outfitGrid.tags.classic': '經典',
    'outfitGrid.tags.trenchCoat': '風衣',
    'outfitGrid.tags.elegant': '優雅',
    'outfitGrid.tags.korean': '韓式',
    'outfitGrid.tags.modern': '現代',
    'outfitGrid.tags.hanbok': '韓服',
    'outfitGrid.tags.gentle': '柔美',
    'outfitGrid.tags.bohemian': '波西米亞',
    'outfitGrid.tags.free': '自由',
    'outfitGrid.tags.layered': '層次',
    'outfitGrid.tags.retro': '復古',
    'outfitGrid.tags.nordic': '北歐',
    'outfitGrid.tags.minimal': '極簡',
    'outfitGrid.tags.quality': '質感',
    'outfitGrid.tags.street': '街頭',
    'outfitGrid.tags.trendy': '潮流',
    'outfitGrid.tags.personality': '個性',
    'outfitGrid.tags.urban': '都市',
    'outfitGrid.tags.business': '商務',
    'outfitGrid.tags.professional': '專業',
    'outfitGrid.tags.fashion': '時尚',
    'outfitGrid.tags.casual': '休閒',
    'outfitGrid.tags.comfortable': '舒適',
    'outfitGrid.tags.daily': '日常',
    'outfitGrid.tags.relaxed': '輕鬆',
    'outfitGrid.tags.evening': '晚宴',
    'outfitGrid.tags.formal': '正式',
    'outfitGrid.tags.luxury': '奢華',

    // Community
    'community.title': '時尚社群',
    'community.subtitle': '與時尚愛好者分享你的穿搭風格，發現無限靈感',
    'community.sortBy': '排序方式',
    'community.latest': '最新發布',
    'community.popular': '最熱門',
    'community.following': '追蹤中',
    'community.filterByTag': '篩選標籤',
    'community.allTags': '所有標籤',
    'community.activeFilters': '篩選條件',
    'community.tag': '標籤',
    'community.login': '登入以參與社群',
    'community.loginDesc': '加入我們的時尚社群，分享你的風格',
    'community.signIn': '使用 Google 登入',
    'community.feed': '搜尋穿搭',
    'community.noOutfits': '還沒有人分享穿搭，成為第一個吧！',
    'community.shareOutfit': '分享穿搭',
    'community.betterThanModel': '喜歡其他人的穿搭?來試試吧!',
    'community.uploadImage': '上傳穿搭圖片',
    'community.addDescription': '新增描述',
    'community.placeholder': '分享你的穿搭心得...',
    'community.submit': '發布',
    'community.cancel': '取消',
    'community.feedTitle': '社群穿搭分享',
    'community.feedSubtitle': '探索社群中最新的時尚穿搭靈感',
    'community.noOutfitsMessage': '目前還沒有任何穿搭分享',
    'community.firstOutfit': '成為第一個分享穿搭的人吧！',
    'community.anonymousUser': '匿名用戶',
    'community.trendingToday': '今日最火穿搭',
    'community.trendingSubtitle': '每日最受歡迎的三則穿搭分享',
    'community.trendingWeek': '本週最火穿搭',
    'community.trendingWeekSubtitle': '每週最受歡迎的三則穿搭分享',
    'community.comments': '留言',
    'community.share': '分享',
    'community.addComment': '新增留言',
    'community.writeComment': '寫下你的想法...',
    'community.postComment': '發送留言',
    'community.loadFail': '載入失敗',
    'community.loginRequired': '請先登入',
    'community.loginToLike': '你需要登入才能按讚',
    'community.loginToComment': '你需要登入才能留言',
    'community.operationFail': '操作失敗',
    'community.shareSuccess': '穿搭分享成功！',
    'community.shareSuccessDesc': '你的穿搭已經發布到社群中',
    'community.shareFail': '發佈失敗',
    'community.editOutfit': '編輯穿搭',
    'community.updateOutfit': '更新穿搭',
    'community.updateSuccess': '穿搭更新成功！',
    'community.updateFail': '更新失敗',
    'community.deleteOutfit': '刪除穿搭',
    'community.shareMyOutfit': '分享我的穿搭',
    'community.shareDesc': '展示你的時尚風格，與社群分享穿搭靈感',
    'community.outfitPhoto': '穿搭照片',
    'community.formTitle': '標題',
    'community.formTitlePlaceholder': '為你的穿搭取個吸引人的標題',
    'community.formDescription': '描述',
    'community.formDescriptionPlaceholder': '分享穿搭的靈感來源、搭配技巧或心得...',
    'community.formStyleTags': '風格標籤',
    'community.formAddStyleTag': '添加風格標籤',
    'community.formUploadPhoto': '點擊上傳照片',
    'community.formSupportFormat': '支援 JPG、PNG 格式',
    'community.publishing': '發布中...',
    'community.publishOutfit': '發布穿搭',
    'community.try': '試穿',
    'community.tryOnConfirmTitle': '試試這個風格？',
    'community.tryOnConfirmDesc': '將會自動跳轉到換裝頁面，並載入這件穿搭照片。您只需要上傳自己的照片就可以嘗試換裝了！',
    'community.yes': '是',
    'community.loadMore': '載入更多...',
    'community.noMoreContent': '已經沒有更多內容了 🎉',
    'community.tryTooltip': '試試這個風格',
    'community.reportTooltip': '舉報',
    'community.shareTooltip': '分享',
    'community.bookmarkTooltip': '收藏',
    'community.unbookmarkTooltip': '取消收藏',

    // Search
    'search.all': '全部',
    'search.users': '用戶',
    'search.posts': '貼文',
    'search.tags': '標籤',
    'search.search': '搜尋',
    'search.searchUsers': '搜尋用戶名稱...',
    'search.searchPosts': '搜尋貼文標題或描述...',
    'search.searchTags': '搜尋標籤...',
    'search.noResults': '沒有找到相關結果',

    // Upload and UI messages
    'upload.fileSizeError': '檔案大小不能超過 10MB',
    'upload.bothPhotosRequired': '請同時上傳全身照片和服裝照片',
    'upload.dragOrClick': '拖拽或點擊上傳',
    'upload.dragOrClickSelect': '拖拽或點擊選擇',
    'upload.supportFormat': '支援 JPG、PNG 格式 · 最佳解析度 1080p+',
    'upload.supportClothing': '服裝、配件、鞋包 · 高清去背佳',
    'upload.privateSafe': '私密安全',
    'upload.instantProcess': '即時處理',
    'upload.aiRecognition': '智能識別',
    'upload.precisionSynthesis': '精準合成',
    'upload.selectFullBodyPhoto': '選擇全身照',
    'upload.selectFashionItem': '選擇時尚單品',
    'upload.completed': '✓ 已完成',
    'upload.selected': '✓ 已選擇',
    'upload.clickToReselect': '點擊重新選擇',
    'upload.clickToChangeStyle': '點擊更換款式',

    // Try-on results
    'tryOn.downloadWork': '點擊查看全圖',
    'tryOn.perfectResult': '完美呈現的虛擬試穿效果',
    'tryOn.tryOnCompleted': '✨ 專屬試穿完成',
    'tryOn.perfectDisplay': '✨ 完美呈現',
    'tryOn.subtitle': '以後連網購都能問，好看嗎？',

    // Case study labels
    'case.originalPhoto': '原始照片',
    'case.professionalPhoto': '專業形象照',
    'case.highQualityPhoto': '高品質全身照片',
    'case.selectedClothing': '精選服飾',
    'case.fashionItem': '時尚單品',
    'case.carefullySelected': '精心挑選的服裝',
    'case.exclusiveResult': '專屬成果',
    'case.perfectTryOnEffect': '完美的虛擬試穿效果',
    'case.luxuryAccessory': '精品配件',
    'case.luxuryItem': '奢華配件',
    'case.selectedAccessory': '精選搭配單品',
    'case.case1': '案例一',
    'case.case2': '案例二',
    'case.case3': '案例三',

    // Footer
    'footer.description': '時尚穿搭分享平台，讓每個人都能展示自己的獨特風格，發現無限時尚靈感。',
    'footer.quickLinks': '快速連結',
    'footer.exploreOutfits': '探索穿搭',
    'footer.fashionTrends': '時尚趨勢',
    'footer.communityGuide': '社群指南',
    'footer.helpCenter': '幫助中心',
    'footer.support': '支援',
    'footer.privacyPolicy': '隱私政策',
    'footer.termsOfUse': '使用條款',
    'footer.contactUs': '聯絡我們',
    'footer.feedback': '意見回饋',
    'footer.copyright': '© 2024 StyleShare. 保留所有權利。',
    'footer.tagline': '讓時尚成為生活的藝術',

    // Features
    'features.title': 'StyleShare',
    'features.subtitle': '我們提供最完整的時尚分享體驗，讓你的穿搭風格被更多人看見與欣賞',
    'features.easyShare': '輕鬆分享',
    'features.easyShareDesc': '一鍵上傳你的穿搭照片，與全世界分享你的時尚品味',
    'features.fashionCommunity': '時尚社群',
    'features.fashionCommunityDesc': '加入充滿活力的時尚愛好者社群，結識志同道合的朋友',
    'features.inspirationCollection': '靈感收藏',
    'features.inspirationCollectionDesc': '收藏喜愛的穿搭，建立屬於你的個人時尚靈感庫',
    'features.trendTracking': '趨勢追蹤',
    'features.trendTrackingDesc': '即時掌握最新時尚趋势，永遠走在潮流前端',
    'features.personalRecommendation': '個性推薦',
    'features.personalRecommendationDesc': 'AI智能推薦符合你風格的穿搭，發現更多可能性',
    'features.tasteRecognition': '品味認證',
    'features.tasteRecognitionDesc': '展示你的時尚影響力，成為社群中的風格指標',

    // Brands
    'brands.title': '精選品牌',
    'brands.subtitle': '探索國際時尚品牌的獨特魅力',
    'brands.comingSoonDesc': '我們正在與更多國際頂級品牌合作，敬請期待更多精彩內容',

    // Celebrities
    'celebrities.title': '時尚名人',
    'celebrities.subtitle': '追隨名人風格，發現穿搭靈感',
    'celebrities.models': '時尚模特',
    'celebrities.influencers': '時尚博主',
    'celebrities.stylists': '造型師',
    'celebrities.featured': '精選名人',
    'celebrities.comingSoonDesc': '即將為您呈現更多時尚名人的精彩穿搭',
    'celebrities.comingSoonDetails': '追蹤您喜愛的名人，獲取最新時尚動態',

    // Common
    'common.loading': '載入中...',
    'common.error': '發生錯誤',

    // Style Changer
    'styleChanger.title': '即刻改造自己',
    'styleChanger.subtitle': 'Get a new YOU!',
    'styleChanger.uploadPhoto': '換你來試試',
    'styleChanger.mission': '我們的任務是讓你知道你能多好看',
    'styleChanger.quickAction1': '即刻改造自己',
    'styleChanger.quickAction2': '試穿室',
    'styleChanger.tryAgain': '再換個風格',
    'styleChanger.trySpecific': '試試指定風格與單品',
    'styleChanger.downloadShare': '喜歡嗎?下載下來Po到IG吧！',
    'styleChanger.selectGender': '選擇性別',
    'styleChanger.male': '男性',
    'styleChanger.female': '女性',
    'styleChanger.missionTitle': 'More outfit More confidence',
    'styleChanger.missionText': '',
    'styleChanger.startJourney': '開始改造旅程',
    'styleChanger.transformShowcaseTitle': '改造過程展示',
    'styleChanger.step1': '原圖',
    'styleChanger.step2': '改造後',
    'styleChanger.communityButton': '穿搭社群',

    // Style Trying
    'styleTrying.title': '試新風格',
    'styleTrying.subtitle': '在這裡換上全新風格',
    'styleTrying.uploadBody': '換你試試',
    'styleTrying.uploadDesc': '',
    'styleTrying.selectGender': '選擇您的性別',
    'styleTrying.selectGenderPlaceholder': '選擇性別',
    'styleTrying.selectStyle': '選擇風格',
    'styleTrying.selectStylePlaceholder': '選擇您喜歡的風格',
    'styleTrying.selectBrand': '選擇品牌',
    'styleTrying.selectBrandPlaceholder': '選擇您喜歡的品牌',
    'styleTrying.genderMale': '男性',
    'styleTrying.genderFemale': '女性',
    'styleTrying.styleRandom': '隨機',
    'styleTrying.styleKorean': '韓系',
    'styleTrying.styleJapanese': '日系',
    'styleTrying.styleAmerican': '美式',
    'styleTrying.styleEuropean': '歐風',
    'styleTrying.selectSeason': '選擇季節',
    'styleTrying.selectSeasonPlaceholder': '請選擇季節',
    'styleTrying.seasonRandom': '隨機',
    'styleTrying.seasonSpring': '春季',
    'styleTrying.seasonSummer': '夏季',
    'styleTrying.seasonAutumn': '秋季',
    'styleTrying.seasonWinter': '冬季',
    'styleTrying.brandRandom': '隨機',
    'styleTrying.processing': '處理中...',
    'styleTrying.startTrying': '開始風格試穿',
    'styleTrying.exclusiveResult': '✨ 專屬風格成果',
    'styleTrying.resultDesc': '完美呈現您的新風格',
    'styleTrying.remainingTryons': '剩餘試穿次數',
    'styleTrying.adminUnlimited': '無限試穿 (管理員)',

    // Profile
    'profile.vipMember': 'VIP 尊享會員',
    'profile.vipPlan': 'VIP 會員方案',
    'profile.vipActive': '啟用中',
    'profile.vipUnlimited': '無限次數虛擬試穿體驗',
    'profile.vipPrice': '限時特惠 $5/月 (原價 $20)',
    'profile.vipDeal': '限時特惠：每月僅需 $5 美元 (原價 $20)',
    'profile.nextBilling': '下次續訂：',
    'profile.subscribe': '立即訂閱',
    'profile.cancelSubscription': '取消訂閱',
    'profile.processing': '處理中',
    'profile.editProfile': '編輯個人資料',
    'profile.uploadingAvatar': '上傳中...',
    'profile.changeAvatar': '更換頭像',
    'profile.nickname': '暱稱',
    'profile.enterNickname': '輸入暱稱',
    'profile.bio': '個人簡介',
    'profile.bioPlaceholder': '介紹一下你自己...',
    'profile.instagram': 'Instagram',
    'profile.enterInstagram': '輸入 Instagram 用戶名',
    'profile.saveChanges': '保存更改',
    'profile.cancel': '取消',
    'profile.outfits': '穿搭',
    'profile.followers': '粉絲',
    'profile.following': '追蹤中',
    'profile.trending': '最火穿搭',
    'profile.remainingTryons': '剩餘試穿次數',
    'profile.lowTryons': '即將用完',
    'profile.unlimited': '無限',
    'profile.sendMessage': '發送訊息',
    'profile.myOutfits': '我的穿搭',
    'profile.bookmarkedOutfits': '收藏的穿搭',
    'profile.noOutfits': '還沒有穿搭作品',
    'profile.firstOutfit': '開始分享你的第一個穿搭吧',
    'profile.publishOutfit': '發佈穿搭',
    'profile.delete': '刪除',
    'profile.confirmDelete': '確認刪除',
    'profile.confirmDeleteDesc': '確定要刪除這個穿搭嗎？此操作無法復原。',
    'profile.confirmCancelSub': '確認取消訂閱',
    'profile.cancelSubDesc': '取消訂閱後將失去以下特權：',
    'profile.cancelSubFeature1': '無限次數虛擬試穿體驗',
    'profile.cancelSubFeature2': 'VIP 會員專屬標識',
    'profile.cancelSubConfirm': '確定要取消訂閱嗎？',
    'profile.keepSubscription': '保留訂閱',
    'profile.confirmCancel': '確認取消',
    'profile.comingSoon': 'Coming Soon',
    'profile.goldMember': '黃金會員',
    'profile.standardAccess': '標準會員',
    'profile.vipBenefits': '無限試穿與專屬特權',
    'profile.standardBenefits': '升級解鎖您的無限潛力',
    'profile.validUntil': '有效期至',
    'profile.lifetime': '終身',
    'profile.tryOns': '試穿次數',
    'profile.vipBadge': 'VIP 徽章',
    'profile.status': '狀態',
    'profile.active': '活躍中',
    'profile.inactive': '未啟用',
    'profile.manageSubscription': '管理訂閱',
    'profile.joinVip': '加入 VIP 俱樂部',

    // Toast messages
    'toast.subscriptionSuccess': '訂閱成功！感謝您成為 VIP 會員！',
    'toast.subscriptionCancelled': '訂閱已取消',
    'toast.profileLoadError': '載入個人資料時發生錯誤',
    'toast.outfitsLoadError': '載入穿搭案例時發生錯誤',
    'toast.profileUpdateSuccess': '個人資料更新成功！',
    'toast.profileUpdateError': '更新個人資料時發生錯誤',
    'toast.avatarUploadSuccess': '頭像上傳成功！',
    'toast.avatarUploadError': '上傳頭像時發生錯誤',
    'toast.subscriptionCreateError': '建立訂閱時發生錯誤，請稍後再試',
    'toast.subscriptionCancelSuccess': '訂閱已成功取消',
    'toast.subscriptionCancelError': '取消訂閱時發生錯誤，請稍後再試',
    'toast.outfitDeleted': '穿搭已刪除',
    'toast.outfitDeleteError': '刪除穿搭時發生錯誤',
    'toast.bookmarksLoadError': '無法載入收藏的穿搭',
    'toast.conversationsLoadError': '無法載入對話列表',
    'toast.messageSendError': '無法發送訊息',
    'toast.pleaseLogin': '請先登入',
    'toast.cannotMessageSelf': '無法與自己對話',
    'toast.conversationCreated': '已建立對話',
    'toast.conversationCreateError': '無法建立對話',
    'toast.registrationComplete': '註冊完成！歡迎加入 StyleShare 社群！',
  },
  en: {
    // Auth
    'auth.subtitle': 'Join the fashion community and share your style',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Your password',
    'auth.passwordTooShort': 'Password must be at least 8 characters',
    'auth.passwordComplexity': 'Password must contain uppercase, lowercase, and number',
    'auth.setPassword': 'Set password',
    'auth.name': 'Name',
    'auth.namePlaceholder': 'Your name',
    'auth.gender': 'Gender',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.preferNotToSay': 'Prefer not to say',
    'auth.birthday': 'Birthday',
    'auth.country': 'Country',
    'auth.selectCountry': 'Select country',
    'auth.loggingIn': 'Logging in...',
    'auth.signingUp': 'Signing up...',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.orDivider': 'OR',

    // Welcome Dialog
    'welcome.title': 'Welcome to StyleShare!',
    'welcome.intro': 'Check out what everyone is wearing in the community! Click "Try" on any post to try on other people\'s outfits.',
    'welcome.tryNewStyle': 'If you want to see how you look with a certain style, go to Virtual Try-On > Try New Style.',
    'welcome.tryNewItem': 'If you have a favorite clothing item photo, go to Virtual Try-On > Try New Item to try it on.',
    'welcome.tryModelOutfit': 'If you see a model photo you like, go to Virtual Try-On > Try Model Outfit to wear the model\'s outfit.',
    'welcome.getStarted': 'Get Started',

    // Header
    'header.home': 'Home',
    'header.virtualTryOn': 'Virtual Try-On',
    'header.community': 'Community',
    'header.brands': 'Brands',
    'header.celebrities': 'Celebrities',
    'header.login': 'Login',
    'header.logout': 'Logout',
    'header.tryNewStyle': 'Try new style',
    'header.tryNewItem': 'Try new item',
    'header.tryModelOutfit': 'Try Model Outfit',
    'header.outfitRating': 'Outfit Rating',
    'header.notificationCenter': 'Notification Center',
    'header.profile': 'Profile',
    'header.adminDashboard': 'Admin Dashboard',
    'header.user': 'User',

    // Outfit Rating
    'outfitRating.title': 'Outfit Rating',
    'outfitRating.subtitle': 'Upload your outfit photo for AI-powered scoring and professional advice',
    'outfitRating.uploadPhoto': 'Upload Outfit Photo',
    'outfitRating.uploadHint': 'Click to upload or drag and drop',
    'outfitRating.rateButton': 'Rate My Outfit',
    'outfitRating.analyzing': 'Analyzing...',
    'outfitRating.noPhoto': 'Please upload a photo first',
    'outfitRating.uploadFirst': 'Please upload your outfit photo first',
    'outfitRating.loginRequired': 'Please login to use outfit rating',
    'outfitRating.error': 'Rating failed',
    'outfitRating.tryAgain': 'Please try again later',
    'outfitRating.detailedFeedback': 'Detailed Feedback',
    'outfitRating.waitingForPhoto': 'Upload a photo to see your rating here',

    // Hero
    'hero.title1': 'Try-on Room',
    'hero.title2': '',
    'hero.subtitle': 'You might not have known how good you could look dressed like this before',
    'hero.onlineTryOn': 'Online Try-On',
    'hero.tagline': 'Stop buying something you have never tried!',
    'hero.experience': 'Try new item',
    'hero.tryNewStyle': 'Try New Style',
    'hero.community': 'Style Community',

    // Virtual Try-On
    'virtualTryOn.title': 'Virtual Try-On Experience',
    'virtualTryOn.personalPhoto': 'Full Body Photo',
    'virtualTryOn.uploadPhoto': 'Upload your photo',
    'virtualTryOn.fashionItems': 'Selected Fashion Items',
    'virtualTryOn.selectOutfit': 'Choose your favorite outfit',
    'virtualTryOn.result': 'Try-On Result',
    'virtualTryOn.startTryOn': 'Start Virtual Try-On',
    'virtualTryOn.processingPercent': 'Changing clothes, wait a moment: {{percent}}%',
    'virtualTryOn.cases': 'Try-On Cases',
    'virtualTryOn.caseDescription': 'See how others look in different outfits',
    'virtualTryOn.loginRequired': 'Please Login',
    'virtualTryOn.loginRequiredDesc': 'You need to login to use the virtual try-on feature',
    'virtualTryOn.shareTitle': 'My Virtual Try-On Result',
    'virtualTryOn.shareDescription': 'Check out my virtual try-on result!',
    'virtualTryOn.shareSuccess': 'Shared Successfully',
    'virtualTryOn.shareSuccessDesc': 'Try-on result has been shared successfully',
    'virtualTryOn.remainingTryons': 'Remaining Try-ons:',
    'virtualTryOn.admin': 'Admin',
    'virtualTryOn.unlimited': 'Unlimited',
    'virtualTryOn.limitReached': 'Usage Limit Reached',
    'virtualTryOn.limitReachedDesc': 'You have used all {count} virtual try-on opportunities',
    'virtualTryOn.tryonSuccess': 'Try-On Successful!',
    'virtualTryOn.tryonSuccessDesc': 'Your virtual try-on photo has been generated. Remaining try-ons: {remaining} / {total}',
    'virtualTryOn.processing': 'Processing',
    'virtualTryOn.processingDesc': 'Workflow started, fetching results…',
    'virtualTryOn.processingFailed': 'Processing Failed',

    // Better Than Model
    'betterThanModel.title': 'Try Model Outfits',
    'betterThanModel.modelOutfits': 'Model Outfit Photos',
    'betterThanModel.selectModelOutfit': 'Choose Your Favorite Model Outfit',
    'betterThanModel.clickToUpload': 'Click to upload photo',
    'betterThanModel.transforming': 'We are changing you.',
    'betterThanModel.estimatedTime': '(Estimated time: 2 mins)',
    'betterThanModel.transformNewStyle': 'Transform New Style',

    // Outfit Grid
    'outfitGrid.title': 'Trending',
    'outfitGrid.titleHighlight': 'Outfits',
    'outfitGrid.subtitle': 'Explore the most popular fashion looks in the community, get inspired, and create your unique style',
    'outfitGrid.loadMore': 'View More Outfits',
    'outfitGrid.outfits.asianSweet': 'Asian Sweet Style',
    'outfitGrid.outfits.europeanClassic': 'European Classic Trench',
    'outfitGrid.outfits.koreanModern': 'Modern Korean Hanbok',
    'outfitGrid.outfits.bohemian': 'Bohemian Vibes',
    'outfitGrid.outfits.nordicMinimal': 'Nordic Minimalist',
    'outfitGrid.outfits.urbanStreet': 'Urban Streetwear',
    'outfitGrid.outfits.businessElegant': 'Elegant Business',
    'outfitGrid.outfits.casualComfort': 'Casual Comfort',
    'outfitGrid.outfits.eveningElegant': 'Evening Elegance',
    'outfitGrid.tags.asian': 'Asian',
    'outfitGrid.tags.sweet': 'Sweet',
    'outfitGrid.tags.floral': 'Floral',
    'outfitGrid.tags.fresh': 'Fresh',
    'outfitGrid.tags.european': 'European',
    'outfitGrid.tags.classic': 'Classic',
    'outfitGrid.tags.trenchCoat': 'Trench',
    'outfitGrid.tags.elegant': 'Elegant',
    'outfitGrid.tags.korean': 'Korean',
    'outfitGrid.tags.modern': 'Modern',
    'outfitGrid.tags.hanbok': 'Hanbok',
    'outfitGrid.tags.gentle': 'Gentle',
    'outfitGrid.tags.bohemian': 'Bohemian',
    'outfitGrid.tags.free': 'Free',
    'outfitGrid.tags.layered': 'Layered',
    'outfitGrid.tags.retro': 'Retro',
    'outfitGrid.tags.nordic': 'Nordic',
    'outfitGrid.tags.minimal': 'Minimal',
    'outfitGrid.tags.quality': 'Quality',
    'outfitGrid.tags.street': 'Street',
    'outfitGrid.tags.trendy': 'Trendy',
    'outfitGrid.tags.personality': 'Edgy',
    'outfitGrid.tags.urban': 'Urban',
    'outfitGrid.tags.business': 'Business',
    'outfitGrid.tags.professional': 'Professional',
    'outfitGrid.tags.fashion': 'Fashion',
    'outfitGrid.tags.casual': 'Casual',
    'outfitGrid.tags.comfortable': 'Comfortable',
    'outfitGrid.tags.daily': 'Daily',
    'outfitGrid.tags.relaxed': 'Relaxed',
    'outfitGrid.tags.evening': 'Evening',
    'outfitGrid.tags.formal': 'Formal',
    'outfitGrid.tags.luxury': 'Luxury',

    // Features
    'features.title': 'StyleShare',
    'features.subtitle': 'We provide the most complete fashion sharing experience, letting your style be seen and appreciated by more people',
    'features.easyShare': 'Easy Sharing',
    'features.easyShareDesc': 'Upload your outfit photos with one click and share your fashion taste with the world',
    'features.fashionCommunity': 'Fashion Community',
    'features.fashionCommunityDesc': 'Join a vibrant community of fashion enthusiasts and meet like-minded friends',
    'features.inspirationCollection': 'Inspiration Collection',
    'features.inspirationCollectionDesc': 'Save your favorite outfits and build your personal fashion inspiration library',
    'features.trendTracking': 'Trend Tracking',
    'features.trendTrackingDesc': 'Stay updated with the latest fashion trends and always stay ahead',
    'features.personalRecommendation': 'Personal Recommendation',
    'features.personalRecommendationDesc': 'AI-powered recommendations that match your style, discover more possibilities',
    'features.tasteRecognition': 'Taste Recognition',
    'features.tasteRecognitionDesc': 'Showcase your fashion influence and become a style icon in the community',

    // Community
    'community.title': 'Fashion Community',
    'community.subtitle': 'Share your outfit styles with fashion lovers and discover endless inspiration',
    'community.login': 'Login to join the community',
    'community.loginDesc': 'Join our fashion community and share your style',
    'community.signIn': 'Sign in with Google',
    'community.feed': 'Search Outfits',
    'community.noOutfits': 'No outfits shared yet. Be the first one!',
    'community.shareOutfit': 'Share Outfit',
    'community.betterThanModel': 'Like Others Outfits? Try Them On!',
    'community.uploadImage': 'Upload outfit image',
    'community.addDescription': 'Add description',
    'community.placeholder': 'Share your outfit thoughts...',
    'community.submit': 'Post',
    'community.cancel': 'Cancel',
    'community.feedTitle': 'Community Style Sharing',
    'community.feedSubtitle': 'Discover the latest fashion outfit inspiration from the community',
    'community.noOutfitsMessage': 'No outfits shared yet',
    'community.firstOutfit': 'Be the first to share an outfit!',
    'community.anonymousUser': 'Anonymous User',
    'community.trendingToday': "Today's Trending Outfits",
    'community.trendingSubtitle': 'The most popular three outfit shares of the day',
    'community.trendingWeek': "This Week's Trending Outfits",
    'community.trendingWeekSubtitle': 'The most popular three outfit shares of the week',
    'community.comments': 'Comments',
    'community.share': 'Share',
    'community.addComment': 'Add Comment',
    'community.writeComment': 'Write your thoughts...',
    'community.postComment': 'Post Comment',
    'community.loadFail': 'Loading Failed',
    'community.loginRequired': 'Please Login',
    'community.loginToLike': 'You need to login to like',
    'community.loginToComment': 'You need to login to comment',
    'community.operationFail': 'Operation Failed',
    'community.shareSuccess': 'Outfit Shared Successfully!',
    'community.shareSuccessDesc': 'Your outfit has been posted to the community',
    'community.shareFail': 'Failed to publish outfit',
    'community.editOutfit': 'Edit Outfit',
    'community.updateOutfit': 'Update Outfit',
    'community.updateSuccess': 'Outfit updated successfully!',
    'community.updateFail': 'Failed to update outfit',
    'community.deleteOutfit': 'Delete Outfit',
    'community.shareMyOutfit': 'Share My Outfit',
    'community.shareDesc': 'Show your fashion style and share outfit inspiration with the community',
    'community.outfitPhoto': 'Outfit Photo',
    'community.formTitle': 'Title',
    'community.formTitlePlaceholder': 'Give your outfit an attractive title',
    'community.formDescription': 'Description',
    'community.formDescriptionPlaceholder': 'Share the inspiration source, matching tips or thoughts about your outfit...',
    'community.formStyleTags': 'Style Tags',
    'community.formAddStyleTag': 'Add style tags',
    'community.formUploadPhoto': 'Click to upload photo',
    'community.formSupportFormat': 'Supports JPG, PNG formats',
    'community.publishing': 'Publishing...',
    'community.publishOutfit': 'Publish Outfit',
    'community.try': 'Try',
    'community.tryOnConfirmTitle': 'Try this style?',
    'community.tryOnConfirmDesc': 'You will be redirected to the try-on page with this outfit loaded. Just upload your photo to try it on!',
    'community.yes': 'Yes',
    'community.loadMore': 'Load More...',
    'community.noMoreContent': 'No more content 🎉',
    'community.tryTooltip': 'Try this style',
    'community.reportTooltip': 'Report',
    'community.shareTooltip': 'Share',
    'community.bookmarkTooltip': 'Bookmark',
    'community.unbookmarkTooltip': 'Remove Bookmark',

    // Upload and UI messages
    'upload.fileSizeError': 'File size cannot exceed 10MB',
    'upload.bothPhotosRequired': 'Please upload both body photo and clothing photo',
    'upload.dragOrClick': 'Drag or click to upload',
    'upload.dragOrClickSelect': 'Drag or click to select',
    'upload.supportFormat': 'Supports JPG, PNG formats · Best resolution 1080p+',
    'upload.supportClothing': 'Clothing, accessories, shoes & bags · High-definition cutout preferred',
    'upload.privateSafe': 'Private & Safe',
    'upload.instantProcess': 'Instant Processing',
    'upload.aiRecognition': 'AI Recognition',
    'upload.precisionSynthesis': 'Precision Synthesis',
    'upload.selectFullBodyPhoto': 'Select Full Body Photo',
    'upload.selectFashionItem': 'Select Fashion Item',
    'upload.completed': '✓ Completed',
    'upload.selected': '✓ Selected',
    'upload.clickToReselect': 'Click to reselect',
    'upload.clickToChangeStyle': 'Click to change style',

    // Try-on results
    'tryOn.downloadWork': 'View Full Image',
    'tryOn.perfectResult': 'Perfect virtual try-on results',
    'tryOn.tryOnCompleted': '✨ Exclusive try-on completed',
    'tryOn.perfectDisplay': '✨ Perfect Display',
    'tryOn.subtitle': 'Now you can even ask when shopping online: Does it look good?',

    // Case study labels
    'case.originalPhoto': 'Original Photo',
    'case.professionalPhoto': 'Professional Portrait',
    'case.highQualityPhoto': 'High-quality full body photo',
    'case.selectedClothing': 'Selected Clothing',
    'case.fashionItem': 'Fashion Item',
    'case.carefullySelected': 'Carefully selected clothing',
    'case.exclusiveResult': 'Exclusive Result',
    'case.perfectTryOnEffect': 'Perfect virtual try-on effect',
    'case.luxuryAccessory': 'Premium Accessory',
    'case.luxuryItem': 'Luxury Accessory',
    'case.selectedAccessory': 'Selected Matching Item',
    'case.case1': 'Case 1',
    'case.case2': 'Case 2',
    'case.case3': 'Case 3',

    // Footer
    'footer.description': 'A fashion sharing platform that allows everyone to showcase their unique style and discover endless fashion inspiration.',
    'footer.quickLinks': 'Quick Links',
    'footer.exploreOutfits': 'Explore Outfits',
    'footer.fashionTrends': 'Fashion Trends',
    'footer.communityGuide': 'Community Guide',
    'footer.helpCenter': 'Help Center',
    'footer.support': 'Support',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfUse': 'Terms of Use',
    'footer.contactUs': 'Contact Us',
    'footer.feedback': 'Feedback',
    'footer.copyright': '© 2024 StyleShare. All rights reserved.',
    'footer.tagline': 'Making fashion the art of life',

    // Brands
    'brands.title': 'Featured Brands',
    'brands.subtitle': 'Explore the unique charm of international fashion brands',
    'brands.comingSoonDesc': 'We are partnering with more international top brands, stay tuned for more exciting content',

    // Celebrities
    'celebrities.title': 'Fashion Celebrities',
    'celebrities.subtitle': 'Follow celebrity styles and discover outfit inspiration',
    'celebrities.models': 'Fashion Models',
    'celebrities.influencers': 'Fashion Influencers',
    'celebrities.stylists': 'Stylists',
    'celebrities.featured': 'Featured Celebrities',
    'celebrities.comingSoonDesc': 'More celebrity fashion looks coming soon',
    'celebrities.comingSoonDetails': 'Follow your favorite celebrities and get the latest fashion updates',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',

    // Style Changer
    'styleChanger.title': 'Unleash Your Style Inspiration',
    'styleChanger.subtitle': 'Get a new YOU!',
    'styleChanger.uploadPhoto': 'Upload a full-body photo, let me help you change your outfit style',
    'styleChanger.mission': 'Our mission is to let you know you look so good.',
    'styleChanger.quickAction1': 'Transform Yourself',
    'styleChanger.quickAction2': 'Virtual Try-On',
    'styleChanger.tryAgain': 'Try Another Style',
    'styleChanger.trySpecific': 'Try Specific Styles & Items',
    'styleChanger.downloadShare': 'Love it? Download & Share on IG!',
    'styleChanger.selectGender': 'Select Gender',
    'styleChanger.male': 'Male',
    'styleChanger.female': 'Female',
    'styleChanger.missionTitle': 'Our mission is to make you more confident',
    'styleChanger.missionText': '',
    'styleChanger.startJourney': 'Start Your Journey',
    'styleChanger.transformShowcaseTitle': 'Transformation Showcase',
    'styleChanger.step1': 'Original',
    'styleChanger.step2': 'After',
    'styleChanger.communityButton': 'Style Community',

    // Style Trying
    'styleTrying.title': 'Try New Style',
    'styleTrying.subtitle': 'Upload your photo, choose your favorite style and brand',
    'styleTrying.uploadBody': '換你試試',
    'styleTrying.uploadDesc': '',
    'styleTrying.selectGender': 'Select Your Gender',
    'styleTrying.selectGenderPlaceholder': 'Select gender',
    'styleTrying.selectStyle': 'Select Style',
    'styleTrying.selectStylePlaceholder': 'Choose your favorite style',
    'styleTrying.selectBrand': 'Select Brand',
    'styleTrying.selectBrandPlaceholder': 'Choose your favorite brand',
    'styleTrying.genderMale': 'Male',
    'styleTrying.genderFemale': 'Female',
    'styleTrying.styleRandom': 'Random',
    'styleTrying.styleKorean': 'Korean Style',
    'styleTrying.styleJapanese': 'Japanese Style',
    'styleTrying.styleAmerican': 'American Style',
    'styleTrying.styleEuropean': 'European Style',
    'styleTrying.selectSeason': 'Select Season',
    'styleTrying.selectSeasonPlaceholder': 'Please select a season',
    'styleTrying.seasonRandom': 'Random',
    'styleTrying.seasonSpring': 'Spring',
    'styleTrying.seasonSummer': 'Summer',
    'styleTrying.seasonAutumn': 'Autumn',
    'styleTrying.seasonWinter': 'Winter',
    'styleTrying.brandRandom': 'Random',
    'styleTrying.processing': 'Processing...',
    'styleTrying.startTrying': 'Start Style Trying',
    'styleTrying.exclusiveResult': '✨ Exclusive Style Result',
    'styleTrying.resultDesc': 'Perfectly presenting your new style',
    'styleTrying.remainingTryons': 'Remaining Try-ons',
    'styleTrying.adminUnlimited': 'Unlimited Try-ons (Admin)',

    // Profile
    'profile.vipMember': 'VIP Premium Member',
    'profile.vipPlan': 'VIP Membership Plan',
    'profile.vipActive': 'Active',
    'profile.vipUnlimited': 'Unlimited virtual try-on experience',
    'profile.vipPrice': 'Limited Offer $5/mo (was $20)',
    'profile.vipDeal': 'Limited Time Offer: Only $5/month (was $20)',
    'profile.nextBilling': 'Next billing:',
    'profile.subscribe': 'Subscribe Now',
    'profile.cancelSubscription': 'Cancel Subscription',
    'profile.processing': 'Processing',
    'profile.editProfile': 'Edit Profile',
    'profile.uploadingAvatar': 'Uploading...',
    'profile.changeAvatar': 'Change Avatar',
    'profile.nickname': 'Nickname',
    'profile.enterNickname': 'Enter nickname',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.instagram': 'Instagram',
    'profile.enterInstagram': 'Enter Instagram username',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.outfits': 'Outfits',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.trending': 'Trending Posts',
    'profile.remainingTryons': 'Remaining Try-ons',
    'profile.lowTryons': 'Running low',
    'profile.unlimited': 'Unlimited',
    'profile.sendMessage': 'Send Message',
    'profile.myOutfits': 'My Outfits',
    'profile.bookmarkedOutfits': 'Bookmarked Outfits',
    'profile.noOutfits': 'No outfits yet',
    'profile.firstOutfit': 'Share your first outfit!',
    'profile.publishOutfit': 'Publish Outfit',
    'profile.delete': 'Delete',
    'profile.confirmDelete': 'Confirm Deletion',
    'profile.confirmDeleteDesc': 'Are you sure you want to delete this outfit? This action cannot be undone.',
    'profile.confirmCancelSub': 'Confirm Cancellation',
    'profile.cancelSubDesc': 'You will lose the following privileges after cancellation:',
    'profile.cancelSubFeature1': 'Unlimited virtual try-on experience',
    'profile.cancelSubFeature2': 'VIP member exclusive badge',
    'profile.cancelSubConfirm': 'Are you sure you want to cancel your subscription?',
    'profile.keepSubscription': 'Keep Subscription',
    'profile.confirmCancel': 'Confirm Cancellation',
    'profile.comingSoon': 'Coming Soon',

    // Toast messages
    'toast.subscriptionSuccess': 'Subscription successful! Thank you for becoming a VIP member!',
    'toast.subscriptionCancelled': 'Subscription cancelled',
    'toast.profileLoadError': 'Error loading profile',
    'toast.outfitsLoadError': 'Error loading outfits',
    'toast.profileUpdateSuccess': 'Profile updated successfully!',
    'toast.profileUpdateError': 'Error updating profile',
    'toast.avatarUploadSuccess': 'Avatar uploaded successfully!',
    'toast.avatarUploadError': 'Error uploading avatar',
    'toast.subscriptionCreateError': 'Error creating subscription, please try again later',
    'toast.subscriptionCancelSuccess': 'Subscription cancelled successfully',
    'toast.subscriptionCancelError': 'Error cancelling subscription, please try again later',
    'toast.outfitDeleted': 'Outfit deleted',
    'toast.outfitDeleteError': 'Error deleting outfit',
    'toast.bookmarksLoadError': 'Unable to load bookmarked outfits',
    'toast.conversationsLoadError': 'Unable to load conversations',
    'toast.messageSendError': 'Unable to send message',
    'toast.pleaseLogin': 'Please login first',
    'toast.cannotMessageSelf': 'Cannot message yourself',
    'toast.conversationCreated': 'Conversation created',
    'toast.conversationCreateError': 'Unable to create conversation',
    'toast.registrationComplete': 'Registration complete! Welcome to StyleShare community!',
    'profile.goldMember': 'Gold Member',
    'profile.standardAccess': 'Standard Access',
    'profile.vipBenefits': 'Unlimited Access & Exclusive Benefits',
    'profile.standardBenefits': 'Upgrade to unlock your full potential',
    'profile.validUntil': 'Valid Until',
    'profile.lifetime': 'Lifetime',
    'profile.tryOns': 'Try-ons',
    'profile.vipBadge': 'VIP Badge',
    'profile.status': 'Status',
    'profile.active': 'Active',
    'profile.inactive': 'Inactive',
    'profile.manageSubscription': 'Manage Subscription',
    'profile.joinVip': 'Join VIP Club',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    const langMap = translations[language] as Record<string, string>;
    const enMap = translations.en as Record<string, string>;
    return (langMap && langMap[key]) || (enMap && enMap[key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};