// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzcdiirglluyrueqllla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Y2RpaXJnbGx1eXJ1ZXFsbGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjYwMzEsImV4cCI6MjA3MzQwMjAzMX0.imDzMyuppCE1SVPvV_tFqyHJyh2RKc23ds_JAXHwTog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});